version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Manish@31
      - DB_NAME=clinic_db
      - JWT_SECRET=4e9d69b8f01b10d6e3815c51f6d21e430cfa91b4582636f546587586b6bd82e7
      - JWT_EXPIRES_IN=1d
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Manish@31
      - MYSQL_DATABASE=clinic_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 